# Generated by Django 5.2.4 on 2025-07-09 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0004_teacher_remove_techer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='teachers.teacher'),
        ),
    ]
