# Generated by Django 5.2.4 on 2025-07-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'TEACHER'), ('student', 'STUDENT'), ('admin', 'ADMIN')], max_length=10),
        ),
    ]
