# Generated by Django 5.2.4 on 2025-07-11 04:23

from django.db import migrations

def truncate_students_and_teachers(apps, schema_editor):
    Student = apps.get_model('students','Student')
    Teacher = apps.get_model('teachers','Teacher')
    User = apps.get_model('accounts','User')

    Student.objects.all().delete()
    Teacher.objects.all().delete()
    User.objects.filter(role__in=["student", "teacher"]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("students", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(truncate_students_and_teachers),
    ]
