# Generated by Django 5.2.4 on 2025-07-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'TEACHER'), ('student', 'STUDENT')], max_length=10),
        ),
    ]
