# Generated by Django 5.2.4 on 2025-07-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Techer',
            new_name='Teacher',
        ),
    ]
