# Generated by Django 5.2.4 on 2025-07-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_assigned_teacher'),
        ('teachers', '0004_teacher_remove_techer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Techer',
        ),
    ]
